-- Abhyudaya cloud schema. Run this once in Supabase: SQL Editor → New query → Run.
create table if not exists users (id uuid primary key, email text unique not null, password_hash text not null, created_at timestamptz not null default now());
create table if not exists characters (user_id uuid primary key references users(id) on delete cascade, name text not null default 'New Operative', class_name text not null default 'Seeker', level integer not null default 1, xp integer not null default 0, gold integer not null default 0, strength integer not null default 1, intellect integer not null default 1, focus integer not null default 1, discipline integer not null default 1, vitality integer not null default 1, creativity integer not null default 1, origin_story text not null default '', directives_json text not null default '[]', protocol text not null default 'balanced', onboarding_completed boolean not null default false, current_streak integer not null default 0, longest_streak integer not null default 0, last_completed_on date, updated_at timestamptz not null default now());
create table if not exists tasks (id uuid primary key, user_id uuid not null references users(id) on delete cascade, title text not null, description text not null default '', attribute text not null check(attribute in ('strength','intellect','focus','discipline','vitality','creativity')), xp_reward integer not null check(xp_reward between 5 and 500), gold_reward integer not null check(gold_reward between 1 and 250), frequency text not null default 'daily', due_date date, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists activity_logs (id uuid primary key, user_id uuid not null references users(id) on delete cascade, type text not null, message text not null, xp_delta integer not null default 0, gold_delta integer not null default 0, created_at timestamptz not null default now());
create table if not exists shop_items (id text primary key, name text not null, description text not null, price integer not null, category text not null, icon text not null);
create table if not exists inventory (user_id uuid not null references users(id) on delete cascade, item_id text not null references shop_items(id), purchased_at timestamptz not null default now(), equipped boolean not null default false, quantity integer not null default 1, primary key(user_id,item_id));
create table if not exists user_settings (user_id uuid primary key references users(id) on delete cascade, sound_enabled boolean not null default true, reduced_motion boolean not null default false, theme text not null default 'cyberpunk', updated_at timestamptz not null default now());
create table if not exists ascension_claims (user_id uuid not null references users(id) on delete cascade, level integer not null, claimed_at timestamptz not null default now(), primary key(user_id,level));
create table if not exists achievement_claims (user_id uuid not null references users(id) on delete cascade, achievement_id text not null, claimed_at timestamptz not null default now(), primary key(user_id,achievement_id));
create table if not exists api_tokens (id uuid primary key, user_id uuid not null references users(id) on delete cascade, token_hash text not null, token_prefix text not null, created_at timestamptz not null default now(), revoked_at timestamptz);
create table if not exists guild_contributions (id uuid primary key, user_id uuid not null references users(id) on delete cascade, kind text not null, amount integer not null default 0, created_at timestamptz not null default now());
create table if not exists guild_state (id integer primary key check(id=1), treasury_gold integer not null default 0, mana integer not null default 0);
insert into guild_state(id) values(1) on conflict do nothing;
insert into shop_items(id,name,description,price,category,icon) values
('hyperfocus-potion','Potion of Hyperfocus','A focus boost for your next quest.',120,'consumable','🧪'),('obsidian-helm','Cyber-Arcane Obsidian Helm','A prestige profile relic.',850,'relic','⛑️'),('neon-terminal','Neon Terminal Theme','Unlock a luminous command-centre theme.',450,'theme','⌘'),('discipline-badge','Iron Discipline Badge','A badge for relentless operatives.',300,'badge','✦'),('ascension-cache','Ascension Cache','Proof of a completed level ascension.',0,'badge','⚡') on conflict do nothing;
create index if not exists tasks_user_created_idx on tasks(user_id, created_at desc);
create index if not exists activity_user_created_idx on activity_logs(user_id, created_at desc);
-- The Vercel backend uses the database password through the transaction pooler. Do not expose tables to browsers.
alter table users enable row level security; alter table characters enable row level security; alter table tasks enable row level security; alter table activity_logs enable row level security; alter table inventory enable row level security; alter table user_settings enable row level security; alter table ascension_claims enable row level security; alter table achievement_claims enable row level security; alter table api_tokens enable row level security; alter table guild_contributions enable row level security; alter table guild_state enable row level security;
