(() => {
  if (!document.querySelector('aside')) return;
  const canvas = document.createElement('canvas'); canvas.id = 'realm-atmosphere'; canvas.setAttribute('aria-hidden', 'true'); document.body.prepend(canvas);
  const style = document.createElement('style'); style.textContent = `#realm-atmosphere{position:fixed;inset:0;width:100%;height:100%;z-index:0;pointer-events:none;opacity:.7;background:radial-gradient(circle at 84% 12%,rgba(41,193,223,.12),transparent 24%),radial-gradient(circle at 55% 85%,rgba(245,158,11,.1),transparent 32%)}body{isolation:isolate}body>aside,body>div,body>header,body>main{position:relative;z-index:1}.realm-pulse{position:fixed;right:24px;bottom:24px;z-index:60;display:flex;align-items:center;gap:8px;padding:9px 12px;border:1px solid rgba(84,221,252,.35);border-radius:999px;background:rgba(6,14,32,.86);color:#acedff;font:700 10px 'Space Grotesk',sans-serif;letter-spacing:.12em;text-transform:uppercase;box-shadow:0 0 22px rgba(84,221,252,.13)}.realm-pulse i{display:block;width:7px;height:7px;border-radius:50%;background:#54ddfc;box-shadow:0 0 12px #54ddfc;animation:realmBlink 1.7s infinite}@keyframes realmBlink{50%{opacity:.25;transform:scale(.65)}}`; document.head.append(style);
  const badge = document.createElement('div'); badge.className = 'realm-pulse'; badge.innerHTML = '<i></i> Realm synchronised'; document.body.append(badge);
  const ctx = canvas.getContext('2d'); let particles=[]; const resize=()=>{canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}; resize(); addEventListener('resize',resize);
  for(let i=0;i<46;i++) particles.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.8+.4,v:Math.random()*.25+.04,a:Math.random()*.55+.1,c:Math.random()>.5?'84,221,252':'255,193,116'});
  const render=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);particles.forEach(p=>{p.y-=p.v;p.x+=Math.sin(p.y*.008)*.09;if(p.y<-6){p.y=innerHeight+6;p.x=Math.random()*innerWidth}ctx.beginPath();ctx.fillStyle=`rgba(${p.c},${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(render)}; render();
  window.realmBurst=(count=42)=>{for(let i=0;i<count;i++){const x=innerWidth*.6,y=innerHeight*.5,angle=Math.random()*Math.PI*2,speed=Math.random()*8+3;particles.push({x,y,r:Math.random()*2+1,v:-Math.abs(Math.sin(angle)*speed),a:1,c:Math.random()>.5?'84,221,252':'255,193,116',burst:1,dx:Math.cos(angle)*speed})}setTimeout(()=>particles=particles.filter(p=>!p.burst).slice(-46),1200)};
})();
